export const ActionTypes = {
  GET_META_MASK_ACCOUNT_LOADING: "GET_META_MASK_ACCOUNT_LOADING",
  GET_META_MASK_ACCOUNT_SUCCESS: "GET_META_MASK_ACCOUNT_SUCCESS",
  GET_META_MASK_ACCOUNT_FAIL: "GET_META_MASK_ACCOUNT_FAIL",

  SET_CONTRACT_INFO_LOADING: "SET_CONTRACT_INFO_LOADING",
  SET_CONTRACT_INFO_SUCCESS: "SET_CONTRACT_INFO_SUCCESS",
  SET_CONTRACT_INFO_FAIL: "SET_CONTRACT_INFO_FAIL",

  ACCEPT_WAGER_LOADING:"ACCEPT_WAGER_LOADING",
  ACCEPT_WAGER_SUCCESS:"ACCEPT_WAGER_SUCCESS",
  ACCEPT_WAGER_FAIL:"ACCEPT_WAGER_FAIL",
};
